module.exports = {
    items: [  
        {  
            id:'123456789',
            user:{
                id:'123456',
                full_name:'Robby Brosman',
                profile_picture:'blah_a.jpg',
                username:'robbybro'
            },
            images:{  
                'thumbnail':{  
                    'width':150,
                    'height':150,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                },
                'low_resolution':{  
                    'width':320,
                    'height':320,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                },
                'standard_resolution':{  
                    'width':640,
                    'height':640,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                }
            },
            created_time:'1497911561',
            caption:{  
                id:'123456',
                text: 'here is a description',
                created_time:'1497911561',
                from:{  
                    id:'123456',
                    full_name:'Robby Brosman',
                    profile_picture:'blah.jpg',
                    username:'robbybro'
                }
            },
            user_has_liked:false,
            likes:{  
                count:45
            },
            tags:[  
                'testdata',
                'js'
            ],
            filter:'Normal',
            comments:{  
                count:0
            },
            type:'image',
            link:'https://www.instagram.com/p/BVibzslgv2R/',
            location:{  
                latitude:0,
                longitude:0,
                name:'uhh... Greenwich?',
                id:123456789
            },
            attribution:null,
            users_in_photo:[  
            ]
        },
        {  
            id:'123456789',
            user:{
                id:'123456',
                full_name:'Robby Brosman',
                profile_picture:'blah_a.jpg',
                username:'robbybro'
            },
            images:{  
                'thumbnail':{  
                    'width':150,
                    'height':150,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                },
                'low_resolution':{  
                    'width':320,
                    'height':320,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                },
                'standard_resolution':{  
                    'width':640,
                    'height':640,
                    'url':'https://scontent.cdninstagram.com/foo.jpg'
                }
            },
            created_time:'1497911561',
            caption:{  
                id:'123456',
                text: 'here is a description',
                created_time:'1497911561',
                from:{  
                    id:'123456',
                    full_name:'Robby Brosman',
                    profile_picture:'blah.jpg',
                    username:'robbybro'
                }
            },
            user_has_liked:false,
            likes:{  
                count:45
            },
            tags:[  
                'testdata',
                'js'
            ],
            filter:'Normal',
            comments:{  
                count:0
            },
            type:'image',
            link:'https://www.instagram.com/p/BVibzslgv2R/',
            location:{  
                latitude:0,
                longitude:0,
                name:'uhh... Greenwich?',
                id:123456789
            },
            attribution:null,
            users_in_photo:[  
            ]
        }
    ],
};